//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Allotment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Allotment()
        {
            this.Rooms = new HashSet<Room>();
        }
    
        public int AllotmentID { get; set; }
        public Nullable<int> AllocatedRooms { get; set; }
        public Nullable<int> ReservedRooms { get; set; }
        public Nullable<int> AvailableRooms { get; set; }
        public Nullable<int> ConferenceID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
        public virtual Conference Conference { get; set; }
    }
}
