//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingConfig
    {
        public int ConferenceID { get; set; }
        public int BookingID { get; set; }
    
        public virtual Configuration Configuration { get; set; }
    }
}
