//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class C_GEM_Payment
    {
        public int AUTOID { get; set; }
        public string BookingID { get; set; }
        public string ClientName { get; set; }
        public string Email { get; set; }
        public string MobileNo { get; set; }
        public string HotelName { get; set; }
        public string RoomCategory { get; set; }
        public Nullable<int> NoofRooms { get; set; }
        public Nullable<int> NoofNights { get; set; }
        public Nullable<double> TotalPrice { get; set; }
        public string Remarks { get; set; }
        public Nullable<bool> TransportRequired { get; set; }
        public string VehicleType { get; set; }
        public string FlightNo { get; set; }
        public Nullable<System.DateTime> ArrivalDate { get; set; }
        public Nullable<System.TimeSpan> ArrivalTime { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public Nullable<System.TimeSpan> DepartureTime { get; set; }
        public string ConventionType { get; set; }
    }
}
