//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation
    {
        public int AUTOID { get; set; }
        public Nullable<int> ConventionID { get; set; }
        public string Cancellation1 { get; set; }
        public string ChargeType { get; set; }
        public Nullable<double> Unit { get; set; }
        public string CancellationNote { get; set; }
    }
}
