//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public int ClientID { get; set; }
        public Nullable<int> ConventionID { get; set; }
        public string title { get; set; }
        public string fullName { get; set; }
        public string Address { get; set; }
        public string country { get; set; }
        public string BookingID { get; set; }
        public string City { get; set; }
        public Nullable<bool> Deligate { get; set; }
        public string ContactNumber { get; set; }
        public string email { get; set; }
        public Nullable<bool> IsUserVerified { get; set; }
        public string Password { get; set; }
    
        public virtual Configuration Configuration { get; set; }
    }
}
