//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class conferencedbEntities : DbContext
    {
        public conferencedbEntities()
            : base("name=conferencedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allotment> Allotments { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Conference> Conferences { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<RoomOccupancy> RoomOccupancies { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<Transport> Transports { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
    }
}
