//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class conferencedbEntities : DbContext
    {
        public conferencedbEntities()
            : base("name=conferencedbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Allotment> Allotments { get; set; }
        public virtual DbSet<BookingConfig> BookingConfigs { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<ConventionHotel> ConventionHotels { get; set; }
        public virtual DbSet<ConventionImage> ConventionImages { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<Deligate> Deligates { get; set; }
        public virtual DbSet<EmailConfiguration> EmailConfigurations { get; set; }
        public virtual DbSet<ExcursionReservation> ExcursionReservations { get; set; }
        public virtual DbSet<Excursion> Excursions { get; set; }
        public virtual DbSet<Hotel> Hotels { get; set; }
        public virtual DbSet<HotelDescription> HotelDescriptions { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Payment_History> Payment_History { get; set; }
        public virtual DbSet<RoomAllotment> RoomAllotments { get; set; }
        public virtual DbSet<RoomDescription> RoomDescriptions { get; set; }
        public virtual DbSet<RoomOccupancy> RoomOccupancies { get; set; }
        public virtual DbSet<RoomRate> RoomRates { get; set; }
        public virtual DbSet<RoomReservation> RoomReservations { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<SystemUser> SystemUsers { get; set; }
        public virtual DbSet<Transport> Transports { get; set; }
        public virtual DbSet<TransportRate> TransportRates { get; set; }
        public virtual DbSet<TransportReservation> TransportReservations { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Cancellation> Cancellations { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
    }
}
