//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuration
    {
        public int AUTOID { get; set; }
        public int ConventionID { get; set; }
        public string RegistrationRequired { get; set; }
        public Nullable<double> RegistrationFees { get; set; }
        public string AccommodationRequired { get; set; }
        public string TransportRequired { get; set; }
        public string ExcursionRequired { get; set; }
    
        public virtual Conference Conference { get; set; }
    }
}
