//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConventionHotel
    {
        public int AUTOID { get; set; }
        public Nullable<int> ConventionID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> HotelDescID { get; set; }
    
        public virtual Configuration Configuration { get; set; }
        public virtual HotelDescription HotelDescription { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
