//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deligate
    {
        public string BookingID { get; set; }
        public string title { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string passportNo { get; set; }
        public string nationality { get; set; }
        public string country { get; set; }
        public Nullable<System.DateTime> arrivalDate { get; set; }
        public string arrivalFlightNo { get; set; }
        public Nullable<System.DateTime> depatureDate { get; set; }
        public string depatureFlightNo { get; set; }
        public int AUTOID { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string address { get; set; }
        public string city { get; set; }
    }
}
