//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcursionReservation
    {
        public int AUTOID { get; set; }
        public Nullable<int> DeligateID { get; set; }
        public Nullable<int> ExcursionID { get; set; }
        public Nullable<System.DateTime> ExcursionDate { get; set; }
        public Nullable<int> NoOfAdults { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Deligate Deligate { get; set; }
        public virtual Excursion Excursion { get; set; }
    }
}
