//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excursion
    {
        public int ExcursionsID { get; set; }
        public Nullable<int> ConventionID { get; set; }
        public string ExcursionName { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string ExcursionImage { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Conference Conference { get; set; }
    }
}
