//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Excursion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Excursion()
        {
            this.ExcursionReservations = new HashSet<ExcursionReservation>();
        }
    
        public int ExcursionsID { get; set; }
        public Nullable<int> ConventionID { get; set; }
        public string ExcursionName { get; set; }
        public string ShortDescription { get; set; }
        public string LongDescription { get; set; }
        public string ExcursionImage { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string TourType { get; set; }
        public string Location { get; set; }
        public Nullable<int> CurID { get; set; }
    
        public virtual Configuration Configuration { get; set; }
        public virtual Currency Currency { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExcursionReservation> ExcursionReservations { get; set; }
    }
}
