//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotelDescription
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotelDescription()
        {
            this.ConventionHotels = new HashSet<ConventionHotel>();
        }
    
        public int DescID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public string ShortDescription { get; set; }
        public string LognDescription { get; set; }
        public string HotelImage { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConventionHotel> ConventionHotels { get; set; }
        public virtual Hotel Hotel { get; set; }
    }
}
