//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int BookingID { get; set; }
        public Nullable<int> HotelID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public Nullable<System.DateTime> BookingDate { get; set; }
        public Nullable<int> ClientID { get; set; }
        public int AUTOID { get; set; }
        public string TransportRequired { get; set; }
        public Nullable<int> TransportID { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual Room Room { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
