//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomAllotment
    {
        public int AUTOID { get; set; }
        public int RoomID { get; set; }
        public int AllotmentID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public int RateID { get; set; }
        public Nullable<int> AvailableRooms { get; set; }
    
        public virtual Allotment Allotment { get; set; }
        public virtual Room Room { get; set; }
        public virtual RoomRate RoomRate { get; set; }
    }
}
