//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomDescription
    {
        public int DescID { get; set; }
        public Nullable<int> RoomID { get; set; }
        public string ShortDescription { get; set; }
        public string LognDescription { get; set; }
        public string RoomImage { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
