//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportRate
    {
        public int RateID { get; set; }
        public Nullable<int> TransportID { get; set; }
        public Nullable<int> VehicleCategory { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> CurCode { get; set; }
    
        public virtual Currency Currency { get; set; }
        public virtual Transport Transport { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
