//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConferencePortal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransportReservation
    {
        public int AUTOID { get; set; }
        public Nullable<int> RateID { get; set; }
        public Nullable<int> NoOfVehicles { get; set; }
        public Nullable<double> Price { get; set; }
        public string TransportType { get; set; }
        public Nullable<System.DateTime> PickUpDate { get; set; }
        public Nullable<System.TimeSpan> PickUpTime { get; set; }
        public Nullable<int> DeligateID { get; set; }
    
        public virtual Deligate Deligate { get; set; }
        public virtual Transport Transport { get; set; }
    }
}
